spring.application.name=api-backend
server.port=8081

# Configuración del Resource Server (Validador de Tokens)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/17dd3345-54db-49ce-8172-092f2ccd50fd/v2.0
spring.security.oauth2.resourceserver.jwt.audience=api://2744e995-bfb7-42ae-8ca7-b4db99e3eaf6