spring.application.name=api-backend
server.port=8081

# Configuración del Resource Server (Validador de Tokens)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/76d5d0d2-dce9-4b35-9913-44753ed0f5cc/v2.0
spring.security.oauth2.resourceserver.jwt.audience=API-Backend-PSilva